// Canonical entry-point body: the single source of truth for every harness bootstrap
// (CLAUDE.md, BASE_BOOTSTRAP.md, .cursor/rules/assistant.mdc, AGENTS.md and the tool
// matrix). Every consumer — `base build`, `base init`, the committed starters — calls THESE
// renderers; none carries a copy.
//
// The files are GENERATED by `base build` from the constants below and gated for freshness in CI,
// so they cannot drift. The policy is deliberately **agent-agnostic**: the entry point is a router, not
// an identity: it never hard-codes a default agent. Routing happens at task boundaries (or on `R`),
// through the deterministic engine (MCP tool first, CLI second), never by the LLM reading a catalogue.

import path from "node:path";
import { compareByCodePoint } from "./ordering.mjs";

export const ROUTER_INTRO =
  "Ce projet est un BASE: des agents et des process en texte. Tu n'as **pas d'identité fixe**; tu es le routeur.";

export const ROUTER_BODY = [
  "## Quand router",
  "- Quand l'utilisateur veut **accomplir une tâche** qui demande un process ou un savoir-faire précis (pas une simple discussion).",
  "- Quand le bon agent/process n'est **pas évident**.",
  "- Quand l'utilisateur écrit **«R»** (ou «R <demande>») pour forcer un routage.",
  "",
  "Cas directs (ne route pas): si l'utilisateur **nomme un agent** («charge l'assistant devis»), ouvre directement son `AGENT.md`. C'est le seul fichier à charger. Et reste dans l'agent déjà chargé: ne route pas à chaque message. Si tu ne peux plus citer le chemin du process actif (après un résumé, ou loin dans une longue conversation), rouvre son `SKILL.md` et l'`AGENT.md` sur disque avant d'agir: le fichier fait foi, pas ta mémoire.",
  "",
  "## Appliquer BASE à un dossier qui n'en est pas encore un",
  "Si l'utilisateur veut faire de SON dossier un BASE (il a du matériel, il veut structurer son savoir et son savoir-faire avec l'IA) et que ce dossier n'a encore ni `base.config.json` ni `.ai/agents/`: ne crée AUCUN fichier à la main. Lance d'abord `base init` (il crée le lanceur, la config, le `CLAUDE.md` et un agent de départ sous `.ai/agents/<nom>/`). Puis route vers `importer-l-existant` (à partir de matériel existant) ou `creer-agent` (de zéro), deux process du cadre BASE et non du dossier de l'utilisateur: le lanceur les atteint via `framework_dir` dans `base.config.json`. Chaque écriture est proposée en diff, jamais committée d'office. Si tu te trouves dans le dépôt du cadre BASE lui-même, n'écris rien ici: initialise plutôt le dossier de l'utilisateur.",
  "",
  "## Comment router",
  "Ta **carte**, c'est l'index généré: si `.ai/routing/index.md` existe, lis-le pour t'orienter. Il liste les agents; l'index de chaque agent (`.ai/agents/<agent>/index.md`, lié depuis la racine) détaille ses process avec «Quand l'utiliser» et «Éviter si». Descends racine → index d'agent → process; retiens le process dont le «Quand l'utiliser» couvre la demande, en respectant «Éviter si». Pour départager, ne lis jamais tous les corps (`AGENT.md`/`SKILL.md`): au plus les métadonnées des candidats (`base discover`, `--projection metadata`, ou le seul bloc frontmatter d'un fichier). Si aucun ne couvre la demande (souvent une question de connaissance, pas une tâche), ne devine pas: `node .ai/base.mjs discover \"<la question>\" --root .` classe les sources (chemins et métadonnées, jamais les corps).",
  "",
  "Le routeur déterministe confirme ton choix et sert de repli (index absent, ou doute). S'il désigne un autre process que le tien, c'est un signal d'ambiguïté: relis les «Quand l'utiliser»/«Éviter si», et si le doute persiste, demande plutôt que de trancher seul. Par ordre de préférence:",
  "1. **Outil MCP `route_request`** (si disponible) → appelle-le, charge l'`AGENT.md` de l'agent retourné, puis le `SKILL.md` du process retourné, et suis ce process.",
  "2. **Sinon, la CLI** (si un terminal est disponible) → `node .ai/base.mjs route \"<demande>\" --root .` depuis la racine du BASE. Ce lanceur est créé par `base init`; il trouve le moteur tout seul (via `framework_dir` dans `base.config.json`), sans rien sur le PATH. Charge ensuite l'agent et le process retournés. **Le même routeur déterministe, sans MCP.**",
  "3. **Sinon** (ni MCP ni terminal) → oriente-toi au plus sur les métadonnées (les blocs frontmatter des candidats), jamais sur une lecture de tous les corps; explique simplement l'intérêt d'un routage déterministe et honnête, et aide l'utilisateur à l'activer: le process `activer-routage` du cadre BASE (sinon la doc du cadre, `mcp/README.md` et `docs/`).",
  "",
  "Une fois routé, précharge ce que le process déclare: `node .ai/base.mjs context \"<process>\" --root .` (ou l'outil MCP `get_context_pack`): des chemins et des notes, jamais les corps; ouvre ensuite seulement ce qui sert.",
  "",
  "Le routeur peut **s'abstenir** (`out_of_scope`, `ambiguous`, `needs_clarification`): pose alors la question qu'il propose, **ne devine pas**, et n'ouvre pas les corps des process concurrents pour trancher: au plus leurs métadonnées. Route d'abord, charge ensuite; aucun agent n'est l'agent par défaut.",
  "",
  "Si une abstention contient un **`fallback`** (un agent → process d'aide), charge ce fallback au lieu de laisser l'utilisateur sans suite: c'est l'accueil/orientation, pas une fausse réponse. S'il n'y a pas de fallback, pose la question proposée ou explique simplement la limite.",
].join("\n");

const GENERATED =
  "<!-- Généré par `base build bootstrap --write`. Ne pas éditer à la main: le corps canonique est dans `tools/core/bootstrap.mjs`. -->";

export function renderClaudeMd() {
  return block([
    "# BASE: Bâtir des Assistants avec une Structure d'Expertise",
    GENERATED,
    `Ce fichier est le **point d'entrée pour Claude Code**. ${ROUTER_INTRO}`,
    ROUTER_BODY,
  ]);
}

export function renderBootstrapMd() {
  return block([
    "# BASE: bootstrap générique",
    GENERATED,
    `Point d'entrée générique pour un harness IA. ${ROUTER_INTRO}`,
    ROUTER_BODY,
  ]);
}

export function renderCursorRule() {
  return block([
    "---\ndescription: BASE: routeur d'agents et de process pour votre métier\nalwaysApply: true\n---",
    GENERATED,
    ROUTER_INTRO,
    ROUTER_BODY,
  ]);
}

// The head of AGENTS.md: the canonical body, ending at the catalogue heading. The generated agent list
// is appended by the build (AGENTS.md is both the AGENTS-family bootstrap and the agent catalogue).
export function renderAgentsHeader() {
  return block([
    "# Agents",
    GENERATED,
    ROUTER_INTRO,
    ROUTER_BODY,
    "## Catalogue des agents",
  ]);
}

function block(parts) {
  return parts.join("\n\n");
}

/** AGENTS.md: the canonical router head followed by the agent catalogue, one line per agent. */
export function renderAgentsMd(resources) {
  const agents = resources
    .filter((resource) => resource.type === "agent")
    .filter((resource) => {
      const normalized = resource.path.split(path.sep).join("/");
      return normalized.startsWith(".ai/agents/") && !normalized.includes("/_");
    })
    .sort((a, b) => compareByCodePoint(a.path, b.path));

  const lines = [renderAgentsHeader(), ""];
  if (agents.length === 0) {
    lines.push("_Aucun agent dans `.ai/agents/`._");
  } else {
    for (const agent of agents) {
      const normalized = agent.path.split(path.sep).join("/");
      // Clean agent name = its directory (".ai/agents/<name>/AGENT.md"), not the slugified path id.
      const name = normalized.split("/").slice(-2, -1)[0] || agent.id;
      lines.push(`- **${name}** - ${agent.description || agent.title} → \`${normalized}\``);
    }
  }
  lines.push("");
  return lines.join("\n");
}

// The MCP-phrased routing discipline — ONE source for the guidance a pure-MCP client re-receives on
// every call. English on purpose: MCP tool descriptions are the one BASE surface read by clients that
// never open the French entry files. These constants and the French body above state the same
// discipline; tests pin the constants verbatim (in renderMcpInstructions AND in the route_request
// description), the freshness gate pins the French projections — neither side can drift silently.
export const MCP_ROUTE_DISCIPLINE =
  "route_request returns a `routing_map` (agents -> processes, each with its «Quand l'utiliser»/«Éviter si») to DECIDE from: the deterministic result is a hint to verify, not an order. " +
  "Choose the process whose «Quand l'utiliser» covers the request; open the chosen agent.path then process.path (open_resource) and follow it. " +
  "If nothing fits, ask the returned next_question (or say so), never guess or invent an id; if the result carries `fallback`, load it the same way. Do not re-route on every message: route at task boundaries.";

export const MCP_READ_DISCIPLINE =
  "Decide on candidate metadata, never by reading all bodies (discover_resources, or open_resource with projection \"metadata\"). " +
  "Once routed, plan what to preload with get_context_pack (paths and notes, never bodies), then open only what serves.";

export const MCP_CONTINUITY =
  "If you can no longer cite the active process path (a long, summarized conversation), " +
  "re-open agent.path then process.path before acting: the files are the source of truth, not your memory.";

/** The fifth projection of the canonical body: the MCP server `instructions` field, composed from the constants above. */
export function renderMcpInstructions() {
  return [
    "This project is a BASE: agents and processes as plain files. You are the router, not an identity.",
    MCP_ROUTE_DISCIPLINE,
    MCP_READ_DISCIPLINE,
    MCP_CONTINUITY,
  ].join("\n\n");
}

export function renderToolMatrix() {
  return [
    "# Matrice des outils BASE",
    "",
    "<!-- Généré par `base build`. Déclaration honnête des garanties atteignables quand l'action passe vraiment par BASE. -->",
    "",
    "Niveaux: 0 non supporté · 1 advisory (guide/audit) · 2 médiation partielle · 3 strict (médié).",
    "",
    "Règle d'honnêteté: cette matrice indique le niveau maximal atteignable par garantie quand",
    "l'action passe vraiment par BASE (CLI, broker, MCP ou connector configuré). Une action qui",
    "contourne BASE reste au niveau natif du harness.",
    "",
    "| Garantie | claude-code | cursor | chatgpt (mcp) | générique |",
    "| --- | --- | --- | --- | --- |",
    "| Confinement des chemins (accès médié) | 3 | 3 | 3 | 1 |",
    "| Confirmation avant écriture (propose/commit) | 3¹ | 2 | 3¹ | 1 |",
    "| Exécution d'outil (dry-run + confirm) | 3¹ | 2 | 3¹ | 1 |",
    "| Découverte native des skills | 3 | 2 | 1 | 1 |",
    "| Hooks / garde-fous mécaniques | 3² | 2² | 0 | 0 |",
    "",
    "¹ Niveau 3 uniquement pour les actions routées par le broker BASE (`propose`/`commit`, `invoke`).",
    "Une écriture ou exécution qui contourne le broker reste advisory.",
    "² Niveau atteignable seulement si le harness est configuré pour router les actions concernées",
    "vers le broker ou un hook. BASE ne livre pas ces hooks pour tous les harnesses.",
    "",
  ].join("\n");
}
